### ISSUE TITLE
Mod is working but don't hide vanilla rendering

### ISSUE THREAD

**Issue by Reotte** [CreativeMD/ItemPhysicLite#1] opened 2020-03-27 13:29 UTC
As shown in picture:
[http://prntscr.com/rntsjc](http://prntscr.com/rntsjc)

Mod List/Pack: [https://www.curseforge.com/minecraft/modpacks/the-lahleepop-craft/](https://www.curseforge.com/minecraft/modpacks/the-lahleepop-craft/)
plus Enhanced Visuals, Blood Fruit, CreativeCore and ItemPhysicLite.

**Comment by CreativeMD** [comment] 2020-03-27 14:26
Weird, it does not happen normally (just tested it again). Can you try to find out which mod is causing it?

**Comment by Reotte** [comment] 2020-03-27 15:58
Sadly, I dont know what causes this. Doesnt look like any mod added affects any visuals. Maybe one of the libraries I have? Since I dont really check what they do, just using them as dependencies.

Currently working on config files of the modpack. After its done I'll try to check in detail.

**Comment by CreativeMD** [comment] 2020-03-27 16:31
I have looked over the mod list as well, couldn't find anything suspicious. I think there is no way around testing it out (remove half of the mods, if it works: take the mods you removed and check them, if it doesn't work: remove another half again).

**Comment by CreativeMD** [comment] 2020-04-04 11:49
any news?

**Comment by Reotte** [comment] 2020-04-05 12:58
Looks like the issue is Obfuscate. Since I read there was issues with it before, I decided to try it first and voila, it fixed after disabling it.

**Comment by Reotte** [comment] 2020-04-05 12:59
By the way, I switched to Full version and issue was still there before trying to disable Obfuscate.

**Comment by CreativeMD** [comment] 2020-04-06 07:50
@MrCrayfish we should really find a solution for this. I don't know what your mod is doing and how. It would be very helpful to have a look at the source code.

**Comment by MrCrayfish** [comment] 2020-04-06 16:59
I've looked into your code, I'm making some changes right now that will create compatibility.

**Comment by CreativeMD** [comment] 2020-04-07 11:51
Perfect, feel free to ask for changes on my end. I have no problem adjusting my code.

**Comment by stonemandave** [comment] 2020-04-11 14:16
Thank you guys for these mods. Both are very well made and essential to me, and I made have said something on both mod posts.

**Comment by CreativeMD** [comment] 2020-04-26 21:40
@Reotte @stonemandave Can you test if the issue is fixed now?

**Comment by stonemandave** [comment] 2020-04-27 00:59
which version i still have problem on 1.15.2 will test 1.12.2 soon

**Comment by MrCrayfish** [comment] 2020-04-27 07:33
Not fixed yet. I just patched a small issue I found in my mod. Still working on compatibility.

**Comment by hopetanner** [comment] 2020-06-02 06:37
When I downloaded the 1.8.9 version I couldn't use it with my other mods. When I looked through to see what was the problem it was because it can't run with Old Animations mod, why is that?

**Comment by CreativeMD** [comment] 2020-10-06 09:46
This issue has been fixed some time ago.

**Closed as completed by CreativeMD** 2020-10-06 09:46 UTC
